/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsCreateRouteImport } from './routes/projects/create'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as OrganizationsCreateRouteImport } from './routes/organizations/create'
import { Route as ContentsContentIdRouteImport } from './routes/contents/$contentId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as OrganizationsOrganizationIdSettingsRouteImport } from './routes/organizations/$organizationId.settings'
import { Route as OrganizationsOrganizationIdMembersRouteImport } from './routes/organizations/$organizationId.members'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCreateRoute = ProjectsCreateRouteImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsCreateRoute = OrganizationsCreateRouteImport.update({
  id: '/organizations/create',
  path: '/organizations/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsContentIdRoute = ContentsContentIdRouteImport.update({
  id: '/contents/$contentId',
  path: '/contents/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const OrganizationsOrganizationIdSettingsRoute =
  OrganizationsOrganizationIdSettingsRouteImport.update({
    id: '/organizations/$organizationId/settings',
    path: '/organizations/$organizationId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdMembersRoute =
  OrganizationsOrganizationIdMembersRouteImport.update({
    id: '/organizations/$organizationId/members',
    path: '/organizations/$organizationId/members',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/contents/$contentId': typeof ContentsContentIdRoute
  '/organizations/create': typeof OrganizationsCreateRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects': typeof ProjectsIndexRoute
  '/organizations/$organizationId/members': typeof OrganizationsOrganizationIdMembersRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/contents/$contentId': typeof ContentsContentIdRoute
  '/organizations/create': typeof OrganizationsCreateRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects': typeof ProjectsIndexRoute
  '/organizations/$organizationId/members': typeof OrganizationsOrganizationIdMembersRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/contents/$contentId': typeof ContentsContentIdRoute
  '/organizations/create': typeof OrganizationsCreateRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/organizations/$organizationId/members': typeof OrganizationsOrganizationIdMembersRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/jobs'
    | '/admin/organizations'
    | '/admin/users'
    | '/contents/$contentId'
    | '/organizations/create'
    | '/projects/$projectId'
    | '/projects/create'
    | '/projects'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/jobs'
    | '/admin/organizations'
    | '/admin/users'
    | '/contents/$contentId'
    | '/organizations/create'
    | '/projects/$projectId'
    | '/projects/create'
    | '/projects'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/jobs'
    | '/admin/organizations'
    | '/admin/users'
    | '/contents/$contentId'
    | '/organizations/create'
    | '/projects/$projectId'
    | '/projects/create'
    | '/projects/'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ContentsContentIdRoute: typeof ContentsContentIdRoute
  OrganizationsCreateRoute: typeof OrganizationsCreateRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  OrganizationsOrganizationIdMembersRoute: typeof OrganizationsOrganizationIdMembersRoute
  OrganizationsOrganizationIdSettingsRoute: typeof OrganizationsOrganizationIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/create': {
      id: '/organizations/create'
      path: '/organizations/create'
      fullPath: '/organizations/create'
      preLoaderRoute: typeof OrganizationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents/$contentId': {
      id: '/contents/$contentId'
      path: '/contents/$contentId'
      fullPath: '/contents/$contentId'
      preLoaderRoute: typeof ContentsContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/organizations/$organizationId/settings': {
      id: '/organizations/$organizationId/settings'
      path: '/organizations/$organizationId/settings'
      fullPath: '/organizations/$organizationId/settings'
      preLoaderRoute: typeof OrganizationsOrganizationIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/members': {
      id: '/organizations/$organizationId/members'
      path: '/organizations/$organizationId/members'
      fullPath: '/organizations/$organizationId/members'
      preLoaderRoute: typeof OrganizationsOrganizationIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminJobsRoute: typeof AdminJobsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminJobsRoute: AdminJobsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ContentsContentIdRoute: ContentsContentIdRoute,
  OrganizationsCreateRoute: OrganizationsCreateRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  OrganizationsOrganizationIdMembersRoute:
    OrganizationsOrganizationIdMembersRoute,
  OrganizationsOrganizationIdSettingsRoute:
    OrganizationsOrganizationIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
